### ISSUE TITLE
Error In Delphi 12

### ISSUE THREAD

**Issue by Saeid2016** [lminuti/Delphi-OpenSSL#15]
Hi, I installed your component in Delphi 12. When I run the demo project it says: can not open "open ssl" library. How should I fix this error?

**Comment by lminuti** [comment]
Do you have the latest release of OpenSSL installed? See: https://docwiki.embarcadero.com/RADStudio/Athens/en/OpenSSL

To install OpenSSL on Windows, you need to copy the libeay32.dll and ssleay32.dll dynamic library files to your file system

**Comment by Saeid2016** [comment]
> Do you have the latest release of OpenSSL installed? See: https://docwiki.embarcadero.com/RADStudio/Athens/en/OpenSSL
> 
> To install OpenSSL on Windows, you need to copy the libeay32.dll and ssleay32.dll dynamic library files to your file system

Yes I installed it by exe installer: [https://slproweb.com/download/Win64OpenSSL-3_4_0.exe](https://slproweb.com/download/Win64OpenSSL-3_4_0.exe) But the problem didn't fix.

My operating system is Windows 10 64 bit.

**Comment by lminuti** [comment]
Delphi-OpenSSL uses the openssl binding from Indy (IdSSLOpenSSLHeaders). At the moment indy supports openssl 1.0.x you can install the DLL from https://github.com/IndySockets/OpenSSL-Binaries

You have to choose the right version: if your app target (and not your OS) is **win32** install [openssl-1.0.2u-i386-win32.zip](https://github.com/IndySockets/OpenSSL-Binaries/blob/master/openssl-1.0.2u-i386-win32.zip) if it's **win64** install [openssl-1.0.2u-x64_86-win64.zip](https://github.com/IndySockets/OpenSSL-Binaries/blob/master/openssl-1.0.2u-x64_86-win64.zip). Then put the two DLLs *libeay32.dll* and *ssleay32.dl* somewhere on your system path or (better) in the same folder of you exe.

**Comment by Saeid2016** [comment]
> Delphi-OpenSSL uses the openssl binding from Indy (IdSSLOpenSSLHeaders). At the moment indy supports openssl 1.0.x you can install the DLL from https://github.com/IndySockets/OpenSSL-Binaries
> 
> You have to choose the right version: if your app target (and not your OS) is **win32** install [openssl-1.0.2u-i386-win32.zip](https://github.com/IndySockets/OpenSSL-Binaries/blob/master/openssl-1.0.2u-i386-win32.zip) if it's **win64** install [openssl-1.0.2u-x64_86-win64.zip](https://github.com/IndySockets/OpenSSL-Binaries/blob/master/openssl-1.0.2u-x64_86-win64.zip). Then put the two DLLs _libeay32.dll_ and _ssleay32.dl_ somewhere on your system path or (better) in the same folder of you exe.

Thank you. The problem fixed. In openssl versions what difference between 1.0.2u, 1.0.2g, 1.0.2s, etc?

**Comment by lminuti** [comment]
Mainly bug fixes: https://github.com/openssl/openssl/blob/master/CHANGES.md#openssl-100
