### ISSUE TITLE
Load public key is still buggy

### ISSUE THREAD

**Issue by jaclas** [lminuti/Delphi-OpenSSL#2]
Load correct public key raise error:

![ashampoo_snap_2016 09 20_10h22m12s_001_](https://cloud.githubusercontent.com/assets/17312717/18662837/419db984-7f1c-11e6-8c2e-aa522de370d7.png)

In the previous version this file has been read (after correcting pchar issue)

I attach a public key file (I change extension from pem to txt)

[key_mf.txt](https://github.com/lminuti/Delphi-OpenSSL/files/482008/key_mf.txt)

**Comment by lminuti** [comment]
I've done a couple of tests with your public key and it seems to work. Can you tell me the exact error message and the version of delphi?

**Comment by jaclas** [comment]
Delphi Berlin
error: [EOpenSSLLibError] PUBKEY load public key error: error:0906D06C:PEM routines:PEM_read_bio:no start line

**Comment by jaclas** [comment]
And?
Please write what version OpenSSL you're using?

**Comment by lminuti** [comment]
I'm using delphi berlin too. My version of OpenSSL is 1.0.2h from https://indy.fulgan.com/SSL/

**Comment by jaclas** [comment]
On 1.0.2h error too:

[EOpenSSLLibError] PUBKEY load public key error: error:0906D06C:PEM routines:PEM_read_bio:no start line

:-(

But when I change your method TRSAPublicKey.LoadFromFile(const FileName: string) by old method:

``` pascal
procedure TRSAPublicKey.LoadFromFile(const FileName: string);
var
  KeyFile :pBIO;
 lFileName: RawByteString;
  pKey :PEVP_PKEY;
begin
  KeyFile := BIO_new(BIO_s_file());

  lFileName := FileName;
  if BIO_read_filename(KeyFile, PAnsiChar(lFileName)) = 0 then
    RaiseOpenSSLError('RSA load file error');
  try
    pKey := PEM_read_bio_PUBKEY(KeyFile, nil, nil, nil);
    if not Assigned(pKey) then
      RaiseOpenSSLError('PUBKEY load public key error');

    try
      FRSA := EVP_PKEY_get1_RSA(pKey);

      if not Assigned(FRSA) then
        RaiseOpenSSLError('RSA load public key error');
    finally
      EVP_PKEY_free(pKey);
    end;
  finally
    BIO_free(KeyFile);
  end;
end;
```

...then error not raised.
This is very strange...

**Comment by TommiPrami** [comment]
That "no start line" error IMHO comes if you don't have : 
-----BEGIN RSA PRIVATE KEY-----
... Key ...
-----END RSA PRIVATE KEY-----

If loading pem key...

or...

-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----

**Comment by TommiPrami** [comment]
Seems that there is an problem after all.

I suddenly started to get same error above, and I've double checked that there was no single code change.

My unit tests started to fail. And same code runs fine on out Jenkins integration build server.

Created new set of keys with OpenSSL. with same result. Something there for sure. No idea why it is behaves this way :(

**Comment by PonyPC** [comment]
@lminuti Create RSA 2048 key or above and under Android can repreduce

**Comment by PonyPC** [comment]
I found the problem position, it is located at OpenSSL.libeay32.pas
the BIO_new_from_stream function is not work correctly.
The Buffer is free by the compiler.

This is my solution: 

function BIO_new_from_stream(AStream: TStringStream): pBIO;
{ var
  Buffer: TBytes; }
begin
  Result := BIO_new_mem_buf(AStream.Memory, AStream.Size);
  { SetLength(Buffer, AStream.Size);
    AStream.ReadBuffer(Buffer[0], AStream.Size);
    Result := BIO_new_mem_buf(Buffer, Length(Buffer)); }
end;

**Comment by lminuti** [comment]
As I said before I cannot reproduce the issue but I think the problem comes from the temporary buffer used as input parameter for `BIO_new_mem_buf`. With that last commit the buffer is persistent, so I think it works.

**Comment by TommiPrami** [comment]
Problem was that it worked perfectly, but stopped working without code changes related to this code. 

I mean this seems very flimsy, on some level.

**Comment by lminuti** [comment]
Yes, it was my fault. I didn't understand the buffer with the certificate data should remain unchanged after the call to `BIO_new_mem_buf`. The documentation states clearly that:

> The supplied data is read directly from the supplied buffer: it is not copied first, so the supplied area of memory must be unchanged until the BIO is freed.

**Comment by TommiPrami** [comment]
Sweet!

**Comment by jaclas** [comment]
and yet... :-)
